# Spring Boot configuration
spring:
  application:
    name: Secure Access
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://testdb-do-user-11229998-0.b.db.ondigitalocean.com:25060/defaultdb
    username: doadmin
    password: AVNS_UDrf2NAddzADTYS6AUp
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #    open-in-view: false
  #    generate-ddl: true
  # Logger configuration
  #logging:
  #  pattern:
  #    console: "%d %-5level %logger : %msg%n"
  #  level:
  #    org.springframework: info
  #    org.hibernate: debug
  mail:
    protocol: smtp
    host: sandbox.smtp.mailtrap.io
    username: 163b4a68900963
    password: 34390a2dce58ca
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #            mail:
  #              protocol: smtp
  #              host: us2.smtp.mailhostbox.com
  #              username: noreply@shortly.tech
  #              password: P*%k)vR2
  #              port: 587
  #              properties:
  #                mail:
  #                  smtp:
  #                    auth: true
  #                    starttls:
  #                      enable: true
  config:
    name: application,config

# Server configuration prod
server:
  port: 8080 #set your port
  address: localhost # set your address
#  enabling character encoding in spring boot
  servlet:
      encoding:
        charset: UTF-8
        force: true


application:
  environment: dev

#  logging configuration
logging:
  file:
    name: secureaccess.log
    path: .



